#*****************************************#
#*                  **                   *#
#*  НАСТРОЙКА ШАХТ  **  DEV: @maxos_666  *#
#*                  **                   *#
#*****************************************#

mines:
  green:
    name: "&aЗелёная шахта" # имя шахты
    region-name: "green_mine" # имя региона, к которому привязана шахта
    recovery: 14400  # время восстановления блоков в шахте (в секундах)
    radius: 0 # радиус проверки игроков (в блоках), установите 0 для отключения
    min-players: 0 # сколько игроков требуется в радиусе, установите 0 для отключения
    work-dates: any # даты, в которые шахта доступна,
                    # укажите any, если шахта доступна в любые даты
  # work-dates: # если нужно указать конкретные даты месяца
  #   - 10
  #   - 15
    breakage-materials: # блоки, которые разрешено ломать в шахте
      DIAMOND_ORE: # материал блока, который разрешено ломать
        drop-materials: # настройка дропа для этого блока (список)
          DIAMOND: # материал предмета, который может выпасть при поломке блока
            chance: 70 # шанс на выпадение этого материала в процентах
            drop-amount: # кол-во материала, которое выпадет при поломке
              # в данном примере выбирается случайное число от 1 до 10
              min: 1 # минимальное кол-во
              max: 10 # максимальное кол-во
          DIAMOND_BLOCK:
            chance: 30
            drop-amount:
              min: 8
              max: 16
      EMERALD_ORE:
        drop-materials:
          EMERALD:
            chance: 70
            drop-amount:
              min: 1
              max: 10
          EMERALD_BLOCK:
            chance: 30
            drop-amount:
              min: 8
              max: 16
    timers: # мск время (диапазоны, в которых шахта открыта) А Я ЕЩЁ НЕ ЕБУ
      - "17:00-23:00"
      - "12:00-15:00"